### ISSUE TITLE
Profile selection seems not to compare complete name

### ISSUE THREAD

**Issue by BitEater21** [composer404/tabby-workspace-manager#6]
When I have for example two profiles: "Profile" & "Profile2" and adding both names to a Workspace Manager Profile, the add-in may open "Profile2" twice. It seems the names are not compared completely?

**Comment by composer404** [comment]
I fixed this issue in version 0.0.4.
@BitEater21 Could you please test it and give me a feedback? :)

**Comment by BitEater21** [comment]
@composer404 I have checked it. Looks better now :)
